#!/usr/bin/env python3
"""Assemble the mirrored dashboard from the reference's own template, CSS and logic.

Inputs (all extracted from the design tool's offline bundle):
  reference.html   the sc-* template, including a <helmet> head block
  logic.js         the Component class (plain JS, zero React)
  manifest.raw     the resource blobs (7 Inter woff2 subsets)

Output:
  leo-program-finance.html   self-contained; no CDN, no third-party runtime
  fonts/*.woff2              self-hosted Inter subsets

The page fetches ./leo_finance_dashboard_data.json at runtime, so the mirror
stays bound to live dbt output rather than freezing a snapshot of it.
"""
import re, os, json, base64, gzip, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import compile as C

OUT = os.path.normpath(os.path.join(HERE, '..', '..', 'site', 'src', 'public'))
REF = open(os.path.join(HERE, 'reference.html'), encoding='utf-8').read()
LOGIC = open(os.path.join(HERE, 'logic.js'), encoding='utf-8').read()
MAN = json.loads(open(os.path.join(HERE, 'manifest.raw'), encoding='utf-8').read().strip())

def require(cond, msg):
    """Every guard below is load-bearing: it is how a changed reference bundle
    becomes a loud build failure instead of a page that quietly lost a link.
    `assert` cannot do that job -- python3 -O (or PYTHONOPTIMIZE=1 in a CI image)
    strips assertions, and this script then exits 0 having silently skipped the
    deviation. Proven: with -O and a one-character change to the Glossary
    button's style, the build "succeeded" with both companion-page links gone."""
    if not cond:
        raise SystemExit('assemble.py: ' + msg)

# ---- 1. split the body into <helmet> (head content) and the real markup -------
body = re.search(r'<body[^>]*>(.*)</body>', REF, re.S).group(1)
body = re.sub(r'<script[\s\S]*?</script>', '', body)
helmet = re.search(r'<helmet>(.*?)</helmet>', body, re.S).group(1)
markup = body.replace(re.search(r'<helmet>.*?</helmet>', body, re.S).group(0), '')
markup = markup.replace('<x-dc>', '').replace('</x-dc>', '').strip()

# ---- 2. font CSS: drop Google preconnects, self-host the woff2 subsets --------
font_css = '\n'.join(re.findall(r'<style[^>]*>(.*?)</style>', helmet, re.S))
# Keep the pre-rewrite text: section 3 strips this block out of page_css by exact
# match, and page_css is read from REF, where the uuids are still bare. Comparing
# against the rewritten copy silently matched nothing and shipped the whole
# helmet block twice -- 31,685 bytes, 9% of the page.
HELMET_CSS_RAW = font_css
# Buffered, not written: the guards below run after this loop, so writing here
# meant a loudly-failed build still rewrote site/src/public/fonts/ while the HTML
# stayed at the previous build -- a committable, inconsistent tree.
PENDING = []
written = 0
for uuid, rec in MAN.items():
    if not rec['mime'].startswith('font/'):
        continue
    raw = base64.b64decode(rec['data'])
    if rec.get('compressed'):
        raw = gzip.decompress(raw)
    PENDING.append((os.path.join(OUT, 'fonts', uuid + '.woff2'), raw))
    font_css = font_css.replace('"%s"' % uuid, '"fonts/%s.woff2"' % uuid)
    written += 1
require('unpkg' not in font_css and 'fonts.g' not in font_css, 'CDN reference survived')
# leo-operations-map.html is hand-authored but wants the same Inter. Emitting the
# @font-face block as a file it can <link> keeps one source for the font faces --
# the alternative was pasting 31KB of rules into a second page and letting them
# drift. This page keeps them inline; it is the self-contained artifact.
#
# The url()s above are document-relative ("fonts/x.woff2") because this page
# inlines them. A stylesheet resolves url() against ITS OWN location, so the
# file version must drop the directory or every face 404s at fonts/fonts/x.woff2
# -- which is exactly what shipped for one build before a network check caught it.
font_css_file = font_css.replace('"fonts/', '"')
require('fonts/' not in font_css_file, 'a document-relative font url survived')
PENDING.append((os.path.join(OUT, 'fonts', 'inter.css'),
    ('/* GENERATED by tools/leo-mirror/assemble.py -- do not hand-edit.\n'
     '   The reference bundle\'s Inter subsets, self-hosted. url()s are relative\n'
     '   to this file, i.e. to fonts/. */\n' + font_css_file).encode('utf-8')))

# ---- 3. the reference's own three style blocks, verbatim ----------------------
page_css = '\n'.join(re.findall(r'<style[^>]*>(.*?)</style>', REF, re.S))
require(HELMET_CSS_RAW in page_css, 'helmet style block not found inside the page styles')
page_css = page_css.replace(HELMET_CSS_RAW, '')    # font block already handled
require('@font-face' not in page_css, 'a font-face rule survived in page_css')
for uuid in [u for u, r in MAN.items() if r['mime'].startswith('font/')]:
    page_css = page_css.replace('"%s"' % uuid, '"fonts/%s.woff2"' % uuid)

# ---- 3b. restore the Operations Map link -------------------------------------
# The reference has no link to the companion page, so mirroring it verbatim left
# leo-operations-map.html with zero inbound links -- unreachable on the live site.
# One anchor, styled from the reference's own Glossary button so it is visually
# native rather than bolted on. This is the single deliberate deviation from the
# byte-exact mirror, and it exists to keep the site navigable.
GLOSSARY_BTN = ('<button sc-camel-on-click="{{ onGloss }}" style="padding:7px 11px;'
                'background:transparent;border:1px solid var(--color-neutral-800);'
                'border-radius:999px;font:500 11px/1 var(--font-body);'
                'color:var(--color-neutral-400);cursor:pointer"')
require(markup.count(GLOSSARY_BTN) == 1, 'Glossary button anchor not found (%d)' % markup.count(GLOSSARY_BTN))
OPS_LINK = ('<a href="leo-operations-map.html" style="padding:7px 11px;'
            'background:transparent;border:1px solid var(--color-neutral-800);'
            'border-radius:999px;font:500 11px/1 var(--font-body);'
            'color:var(--color-neutral-400);cursor:pointer;text-decoration:none;'
            'display:inline-flex;align-items:center" '
            'style-hover="border-color:var(--color-accent-700);color:var(--color-text)">'
            'Operations Map</a>\n\n        ')
markup = markup.replace(GLOSSARY_BTN, OPS_LINK + GLOSSARY_BTN, 1)

# ---- 3c. accessibility + navigation repairs -----------------------------------
# Deliberate deviations from the byte-exact mirror, all in the same category as
# the Operations Map link: the reference is a design artifact, this is a live
# page on a public site and has to be navigable and announceable.

# (a) toggle state must be announced. __e() renders false as '', so the value is
#     built as an explicit string rather than bound to the raw boolean.
for handler, flag in (('onPlain', 'plain'), ('onGloss', 'gloss'), ('onTour', 'tour')):
    needle = '<button sc-camel-on-click="{{ %s }}"' % handler
    require(markup.count(needle) == 1, 'toggle %s not found (%d)' % (handler, markup.count(needle)))
    markup = markup.replace(
        needle,
        '<button sc-camel-on-click="{{ %s }}" aria-pressed="{{ %s ? \'true\' : \'false\' }}"' % (handler, flag),
        1)

# (b) the dbt docs are orphaned site-wide without this link
DOCS_LINK = OPS_LINK.replace('leo-operations-map.html', 'leo-dbt-docs/').replace('Operations Map', 'Data Lineage')
markup = markup.replace(OPS_LINK, OPS_LINK + DOCS_LINK, 1)

# (c) the home link was absolutised to the production URL, so opening the page
#     locally or from a fork navigated away to the live site
ABS_HOME = 'href="https://tjaiyen.github.io/tj-finance-portfolio/"'
require(markup.count(ABS_HOME) == 1, 'home link not found (%d)' % markup.count(ABS_HOME))
markup = markup.replace(ABS_HOME, 'href="./"', 1)

# (d) the header control cluster is a nowrap flex row. In the reference that is
#     fine -- a design artifact is viewed at desktop width -- but on a live page
#     it forced 588px of controls through a 375px viewport and the whole
#     document scrolled sideways. (The two links added above widen it to 752px;
#     they are not the cause, removing them still overflows.) One property, and
#     it changes nothing at any width where the row already fitted.
BAR = 'style="display:flex;align-items:center;gap:8px;flex:0 0 auto"'
require(markup.count(BAR) == 1, 'header control cluster not found (%d)' % markup.count(BAR))
markup = markup.replace(
    BAR, 'style="display:flex;align-items:center;gap:8px;flex:0 1 auto;flex-wrap:wrap"', 1)

# ---- 3d. table semantics ------------------------------------------------------
# The reference draws every table as CSS Grid divs, so the page this mirror
# replaced lost all of its tabular structure: 92 <th> became unlabelled <span>.
# Real <table> markup cannot come back without destroying the grid layout, so
# the semantics are restored with ARIA roles instead -- identical announcement
# to a screen reader, zero visual change.
#
# Only grids that are genuinely tabular are touched, and "tabular" here means
# "has a real header row". Deliberately left alone: repeat(auto-fit,...) grids
# (responsive card layouts, not tables), the headerless row lists (EAC
# Sensitivity, Cost-Driver Pareto, Efficiency Trend), the Risk Register's card
# rows, and the Cash-Flow group toggles (each row is a disclosure <button>;
# role="row" would destroy the button).
TABLE_GRIDS = [
    '1.4fr .7fr .8fr .8fr .8fr repeat(4,.7fr) .8fr',                # Rolling Variance Trend
    'minmax(160px,2fr) .8fr .8fr .8fr .6fr .8fr .6fr .6fr',         # Cash-Flow, per expanded group
    'minmax(110px,1fr) repeat(5,1fr)',                              # Capitalised Inventory Roll-Forward
    ('minmax(96px,.8fr) minmax(150px,1.4fr) minmax(160px,1.8fr) '
     'minmax(120px,1.1fr) minmax(100px,.9fr)'),                     # Operational KPI Framework
    '78px 1fr 52px 44px',                                           # Program Delivery Risk Index
    'minmax(150px,1.5fr) minmax(160px,1.6fr) minmax(180px,2fr)',    # Mitigation Roadmap
]

_VOID = {'br', 'hr', 'img', 'input', 'meta', 'link', 'source', 'use', 'stop', 'col'}
_TAG = re.compile(r'<(/?)([\w-]+)((?:"[^"]*"|[^>"])*?)(/?)>', re.S)


class _El(object):
    __slots__ = ('tag', 'attrs', 'start', 'parent', 'kids')

    def __init__(self, tag, attrs, start, parent):
        self.tag, self.attrs, self.start, self.parent, self.kids = tag, attrs, start, parent, []

    @property
    def style(self):
        m = re.search(r'\bstyle="([^"]*)"', self.attrs)
        return m.group(1) if m else ''


def _parse(src):
    """Tag tree. sc-for / sc-if are kept as nodes; they vanish at compile time,
    so the walkers below step over them to get the element that will really be
    the parent in the rendered DOM."""
    root = _El('#root', '', 0, None)
    stack = [root]
    for m in _TAG.finditer(src):
        closing, tag, attrs, selfclose = m.groups()
        if closing:
            for i in range(len(stack) - 1, 0, -1):
                if stack[i].tag == tag:
                    del stack[i:]
                    break
            continue
        el = _El(tag, attrs, m.start(), stack[-1])
        stack[-1].kids.append(el)
        if not selfclose and tag not in _VOID:
            stack.append(el)
    return root


def _every(el, out):
    out.append(el)
    for k in el.kids:
        _every(k, out)
    return out


def _eff_kids(el):
    out = []
    for k in el.kids:
        out.extend(_eff_kids(k) if k.tag in ('sc-for', 'sc-if') else [k])
    return out


def _eff_parent(el):
    p = el.parent
    while p is not None and p.tag in ('sc-for', 'sc-if'):
        p = p.parent
    return p


def _cols(spec):
    """Column count of a grid-template-columns value (repeat() expanded)."""
    parts, depth, buf = [], 0, ''
    for ch in spec:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ' ' and depth == 0:
            if buf:
                parts.append(buf)
            buf = ''
        else:
            buf += ch
    if buf:
        parts.append(buf)
    n = 0
    for p in parts:
        m = re.match(r'repeat\((\d+),', p)
        n += int(m.group(1)) if m else 1
    return n


def _table_roles(src):
    allel = _every(_parse(src), [])
    ins = {}                       # element start offset -> role
    def put(el, role):
        pos = el.start + 1 + len(el.tag)
        require(ins.get(pos, role) == role, 'conflicting role at %d' % pos)
        ins[pos] = role

    for spec in TABLE_GRIDS:
        needle = 'grid-template-columns:%s;' % spec
        rows = [e for e in allel if 'display:grid' in e.style and needle in e.style]
        # one header row plus one row template per table; a change to the
        # reference that breaks this should fail loudly, not silently skip
        require(len(rows) == 2, '%r: %d row nodes, expected 2' % (spec[:40], len(rows)))
        container = min((_eff_parent(r) for r in rows), key=lambda p: p.start)
        ncols = _cols(spec)
        headers = 0
        for r in rows:
            # anything between the container and the row is a scroll wrapper or
            # similar; it has to be a rowgroup or it breaks the owned structure
            node, in_loop = r.parent, False
            while node is not container:
                require(node is not None, '%r: container is not an ancestor' % spec[:40])
                if node.tag == 'sc-for':
                    in_loop = True
                elif node.tag != 'sc-if':
                    put(node, 'rowgroup')
                node = node.parent
            cells = _eff_kids(r)
            require(len(cells) == ncols, '%r: %d cells, %d columns' % (spec[:40], len(cells), ncols))
            for c in cells:
                put(c, 'cell' if in_loop else 'columnheader')
            put(r, 'row')
            headers += 0 if in_loop else 1
        require(headers == 1, '%r: %d header rows' % (spec[:40], headers))
        put(container, 'table')

    for pos in sorted(ins, reverse=True):
        src = src[:pos] + ' role="%s"' % ins[pos] + src[pos:]
    return src, ins


markup, _roles = _table_roles(markup)

# the KPI header cells are <button>s, so role="columnheader" costs them their
# announced button role. aria-sort gives the sort affordance back. Every
# comparator in logic.js is ascending; the buttons pick the active column, they
# do not flip direction.
for handler, flag in (('kpiSortDom', 'kpiSort.domain'),
                      ('kpiSortName', 'kpiSort.name'),
                      ('kpiSortStat', 'kpiSort.status')):
    needle = '<button role="columnheader" sc-camel-on-click="{{ %s }}"' % handler
    require(markup.count(needle) == 1, 'KPI header %s not found (%d)' % (handler, markup.count(needle)))
    markup = markup.replace(
        needle,
        needle + ' aria-sort="{{ %s ? \'ascending\' : \'none\' }}"' % flag, 1)

# ---- 3e. mobile: three grids are wider than a phone ---------------------------
# Risk Register (200+120+80+80 = 564px), Mitigation Roadmap (538px) and Cost
# Pareto (390px) declare column minimums that cannot fit 375px, so the whole
# document scrolled sideways. The reference has no media queries and every grid
# is an inline style, so this targets the inline style by substring and collapses
# those three to a single column -- no markup surgery, and nothing changes at any
# width where the row already fitted. Headers stay visible: hiding them would
# drop the columnheader roles out of the accessibility tree.
STACK_AT = [
    'minmax(200px,2fr) minmax(120px,1fr)',              # Risk Register
    'minmax(150px,1.5fr) minmax(160px,1.6fr)',          # Mitigation Roadmap
    '26px minmax(150px,1.8fr)',                         # Cost-Driver Pareto
]
for _sel in STACK_AT:
    require(_sel in markup, 'mobile stack target not found: %s' % _sel)
MOBILE_CSS = '@media (max-width:560px){\n%s{grid-template-columns:1fr !important}\n}' % (
    ',\n'.join('[style*="%s"]' % _sel for _sel in STACK_AT))

# ---- 4. compile the template -------------------------------------------------
tpl_body = C.compile_frag(markup)
hover_css = '\n'.join('.%s:hover{%s}' % (cls, rules) for rules, cls in C.hover_rules.items())

# ---- 5. DCLogic shim: setState + lifecycle + one delegated event dispatcher ---
SHIM = r'''
// Minimal stand-in for the design tool's component base class. The reference's
// logic only ever uses setState + the three lifecycle hooks, so that is all this
// provides -- no template engine, no eval, no CDN loader.
function DCLogic(props){ this.props = props || {}; }
DCLogic.prototype.setState = function(patch, cb){
  Object.assign(this.state, typeof patch === 'function' ? patch(this.state) : patch);
  this.__render();
  if (cb) cb();
};

function __scope(V){
  return new Proxy(V, {
    // Own keys only. `k in t` walks the prototype chain (claiming constructor,
    // toString, ...) and, worse, lets the 100-odd names renderVals() omits on its
    // pre-data early return escape to the GLOBAL scope. hasOwnProperty keeps the
    // boundary exactly at what V defines, while still leaving real globals
    // (Math, JSON) reachable for a future template expression.
    has: function(t, k){
      return Object.prototype.hasOwnProperty.call(t, k)
        && k !== '__h' && k !== '__e' && k !== '__g' && k !== '__u' && k !== '__a';
    },
    get: function(t, k){ return k === Symbol.unscopables ? undefined : t[k]; }
  });
}

// Replacing the whole subtree on every setState was the single root cause of
// six separate defects: reveal/draw animations replayed on every click, the
// tour's smooth scroll was cancelled, a dragged range input lost pointer
// capture, focus and ARIA state were destroyed, the ResizeObserver ended up
// watching a detached node, and IntersectionObserver targets grew unboundedly.
// Patching in place keeps node identity, so all six stop happening.
//
// data-in is set imperatively by reveal() and never emitted by the template, so
// it is preserved rather than diffed away -- otherwise every patch would strip
// it and restart the CSS animations it gates.
var PRESERVE_ATTRS = { 'data-in': 1 };
// id is the mount HOST's own, set in the page shell and never emitted by the
// template -- without this the first patch strips it and #leo-app stops
// resolving for CSS, deep links and tests. Root only: a descendant that
// legitimately drops its id should lose it.
var PRESERVE_ROOT_ATTRS = { 'id': 1 };

function morph(oldEl, newEl, isRoot){
  // attributes
  var oldAttrs = oldEl.attributes, i, a;
  for (i = oldAttrs.length - 1; i >= 0; i--){
    a = oldAttrs[i].name;
    if (!newEl.hasAttribute(a) && !PRESERVE_ATTRS[a]
        && !(isRoot && PRESERVE_ROOT_ATTRS[a])) oldEl.removeAttribute(a);
  }
  for (i = 0; i < newEl.attributes.length; i++){
    a = newEl.attributes[i];
    if (oldEl.getAttribute(a.name) !== a.value) oldEl.setAttribute(a.name, a.value);
  }
  // a live control's value is user state, not template state -- only push a
  // genuinely different value so a caret or an in-flight drag is not disturbed
  if (oldEl.tagName === 'INPUT' || oldEl.tagName === 'SELECT' || oldEl.tagName === 'TEXTAREA'){
    var nv = newEl.getAttribute('value');
    if (nv != null && oldEl.value !== nv && document.activeElement !== oldEl) oldEl.value = nv;
  }
  // children -- keyed where compile.py stamped a data-k, positional otherwise.
  // Position alone is wrong as soon as siblings are added, removed or reordered:
  // the tour's Back/Next/Finish realign so the node focused as Next renders
  // Back, and unpinning leaves focus on a node now holding a different pin.
  var keyed = null, ki, kv;
  for (ki = 0; ki < oldEl.children.length; ki++){
    kv = oldEl.children[ki].getAttribute('data-k');
    if (kv) { (keyed || (keyed = {}))[kv] = oldEl.children[ki]; }
  }
  var o = oldEl.firstChild, n = newEl.firstChild, oNext, nNext, match;
  while (o || n){
    oNext = o && o.nextSibling; nNext = n && n.nextSibling;
    if (!n){ oldEl.removeChild(o); }
    else if (!o){ oldEl.appendChild(n); }
    else {
      kv = n.nodeType === 1 ? n.getAttribute('data-k') : null;
      if (kv && keyed && keyed[kv] && keyed[kv] !== o){
        // this identity already exists further along -- move it here rather
        // than overwriting whatever happens to sit at this position
        match = keyed[kv];
        oldEl.insertBefore(match, o);
        morph(match, n, false);
        n = nNext;
        continue;                       // o still needs a partner
      }
      if (o.nodeType !== n.nodeType || o.nodeName !== n.nodeName){
        oldEl.replaceChild(n, o);
      } else if (o.nodeType === 3){
        if (o.nodeValue !== n.nodeValue) o.nodeValue = n.nodeValue;
      } else if (o.nodeType === 1){
        morph(o, n, false);
      }
    }
    o = oNext; n = nNext;
  }
}

var __handlers = [];
function __h(fn){ __handlers.push(fn); return __handlers.length - 1; }
function __g(thunk){ try { return thunk(); } catch(e) { return undefined; } }
function __esc(s){
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
function __e(thunk){
  var v = __g(thunk);
  if (v == null || v === false || typeof v === 'function') return '';
  return __esc(v);
}
// href values come from dbt output and are https today, so this is a guard
// rather than a fix: a scheme allowlist keeps a future data change from
// turning a link into javascript:/data: execution. Relative paths and
// fragments pass; anything carrying a scheme that is not http(s) renders as
// an empty href. Control characters are stripped first because browsers
// ignore them inside a URL, so java\nscript: would otherwise slip through.
// An <a> whose data has no URL used to render href="", which resolves to the
// current page -- with target="_blank" that opened a second copy of the page in
// a new tab. Emitting the whole attribute or nothing makes it inert instead.
function __a(name, thunk){
  var v = __u(thunk);
  return v ? name + '="' + v + '"' : '';
}
function __u(thunk){
  var v = __g(thunk);
  if (typeof v !== 'string') return '';
  var s = v.replace(/[\u0000-\u0020]/g, '');
  if (!/^(?:https?:\/\/|\/\/|[#?\/])/i.test(s) && /^[\w.+-]*:/.test(s)) return '';
  return __esc(s);
}

// --- shareable state ---------------------------------------------------------
// The whole point of a scenario slider is being able to send someone what you
// were looking at. State goes in the hash, and comes back out of it -- but the
// hash is attacker-controllable, so every value is validated against a closed
// set or clamped before it reaches state (B13: a URL is data, not instruction).
var URL_ENUMS = {
  scen:    ['low', 'base', 'high'],
  kpiSort: ['domain', 'name', 'status'],
  rrSort:  ['exposure', 'cat', 'name']
};
var URL_KEYS = ['scen', 'rate', 'plain', 'kpiDom', 'kpiStat', 'kpiSort', 'rrSort'];

function readHash(){
  var out = {}, h = location.hash.replace(/^#/, '');
  if (!h) return out;
  h.split('&').forEach(function(pair){
    var i = pair.indexOf('='); if (i < 0) return;
    var k, v;
    try { k = decodeURIComponent(pair.slice(0, i)); v = decodeURIComponent(pair.slice(i + 1)); }
    catch (e) { return; }                       // malformed escape: ignore the pair
    if (URL_KEYS.indexOf(k) < 0) return;
    if (URL_ENUMS[k]) { if (URL_ENUMS[k].indexOf(v) >= 0) out[k] = v; return; }
    if (k === 'plain') { out[k] = v === '1'; return; }
    if (k === 'rate') {
      var n = parseFloat(v);
      if (isFinite(n)) out[k] = Math.min(5, Math.max(0.5, n));   // clamp to the slider's range
      return;
    }
    // kpiDom / kpiStat are matched with === against real values, so an unknown
    // string simply filters to nothing rather than doing anything interesting
    if (v.length <= 60) out[k] = v;
  });
  return out;
}

function writeHash(state){
  var parts = [];
  URL_KEYS.forEach(function(k){
    var v = state[k];
    if (v == null) return;
    if (k === 'plain') { if (v) parts.push('plain=1'); return; }
    parts.push(encodeURIComponent(k) + '=' + encodeURIComponent(v));
  });
  var h = '#' + parts.join('&');
  if (h !== location.hash) {
    // replaceState, not a hash assignment: no scroll jump, no history spam
    history.replaceState(null, '', location.pathname + location.search + h);
  }
}

(function mount(){
  var host = document.getElementById('leo-app');
  var inst = new Component({
    // the exported prop schema's declared defaults -- 'high' is what the
    // reference itself boots into (5.0/day ceiling, 100% utilisation)
    defaultScenario: 'high', plainEnglishDefault: false,
    motion: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'reduced' : 'full'
  });
  var fromUrl = readHash(), urlDirty = false;
  function applyUrl(){
    for (var k in fromUrl) {
      if (Object.prototype.hasOwnProperty.call(fromUrl, k)) inst.state[k] = fromUrl[k];
    }
  }
  applyUrl();
  var first = true;
  inst.__render = function(){
    // Build into a LOCAL handler array and publish it only once the whole
    // template has rendered. The old code cleared __handlers first, so a throw
    // anywhere in renderVals()/__tpl left the page looking fully loaded and
    // completely inert: every data-ev-* index pointed into an empty array, no
    // control responded, and no banner appeared -- hasErr only covers a failed
    // fetch or JSON parse, not a failed render.
    // The link wins until the reader changes something. A one-shot re-apply was
    // not enough: the marts setState runs afterData(), which re-derives rate
    // from the scenario and clobbered it (measured -- #rate=1.25 came back 5).
    if (!urlDirty) applyUrl();
    var local = [], V, html;
    try {
      V = inst.renderVals();
      html = __tpl(V, function(fn){ local.push(fn); return local.length - 1; },
                   __e, __g, __u, __a);
    } catch (e) {
      if (!inst.state.err) {
        // clearing d sends renderVals down its early-exit path, so the error
        // banner can actually render instead of re-entering the same throw
        inst.setState({ d: null, err: 'render failed: ' + String(e && e.message || e) });
      }
      return;
    }
    __handlers = local;
    // A control that removes itself on activation (the KPI "Clear" button, the
    // last pinned chip) used to drop focus to <body>, restarting Tab from the
    // top of the document. Remember the path to the focused node first, then
    // land on the nearest ancestor that survived the patch.
    var active = document.activeElement, path = [];
    if (active && host.contains(active)) {
      for (var n = active; n && n !== document.body; n = n.parentElement) path.push(n);
    }
    if (first){ host.innerHTML = html; first = false; }
    else {
      var next = document.createElement('div');
      next.innerHTML = html;
      morph(host, next, true);
      if (path.length && document.activeElement === document.body) {
        for (var i = 0; i < path.length; i++) {
          if (path[i].isConnected) {
            if (!path[i].hasAttribute('tabindex')
                && !/^(A|BUTTON|INPUT|SELECT|TEXTAREA)$/.test(path[i].tagName)) {
              path[i].setAttribute('tabindex', '-1');
            }
            path[i].focus();
            break;
          }
        }
      }
    }
    if (urlDirty) writeHash(inst.state);
    if (inst.componentDidUpdate) inst.componentDidUpdate();
  };
  // One delegated listener for every data-ev-* the template emitted, so no
  // executable code is ever written into an attribute.
  ['click','input','change'].forEach(function(type){
    host.addEventListener(type, function(ev){
      var el = ev.target.closest('[data-ev-' + type + ']');
      if (!el) return;
      var fn = __handlers[+el.getAttribute('data-ev-' + type)];
      if (typeof fn === 'function') { urlDirty = true; fn(ev); }
    });
  });
  // run() derives its target by reading the element it is animating. The original
  // runtime patches nodes in place, so that is safe; this renderer replaces them,
  // and a re-render mid-animation would make run() read its own interpolated value
  // back as the new target and freeze there. Arm the count-up once, after data
  // lands, and let later updates paint final values directly.
  var _counters = inst.counters, countersArmed = false;
  inst.counters = function(){
    if (countersArmed || !this.state.d) return;
    countersArmed = true;
    return _counters.call(this);
  };

  inst.__render();
  if (inst.componentDidMount) inst.componentDidMount();
  window.addEventListener('beforeunload', function(){
    if (inst.componentWillUnmount) inst.componentWillUnmount();
  });
})();
'''

HEAD_EXTRA = '''<meta name="description" content="A Finance Manager's view of Amazon's Leo satellite programme: milestone risk, capital escalation, EVM and the build-vs-launch gap, modelled from public disclosures with dbt + DuckDB.">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%9B%B0%EF%B8%8F%3C/text%3E%3C/svg%3E">'''

html = (
    '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
    '<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    '<title>Leo Program Finance — dbt + DuckDB</title>\n'
    + HEAD_EXTRA + '\n'
    '<style>\n' + font_css + '\n</style>\n'
    '<style>\n' + page_css + '\n</style>\n'
    '<style>\n' + hover_css + '\n' + MOBILE_CSS + '\n</style>\n'
    '</head>\n<body>\n'
    '<div id="leo-app"></div>\n'
    '<script>\n'
    '// GENERATED: the design reference\'s own template + logic, compiled to plain JS.\n'
    '// Source of truth is the exported design; regenerate with assemble.py.\n'
    '(function(){\n'
    + LOGIC + '\n'
    + 'function __tpl(V, __h, __e, __g, __u, __a){ with(__scope(V)){ return `' + tpl_body + '`; } }\n'
    + SHIM +
    '})();\n'
    '</script>\n</body>\n</html>\n'
)

# every guard passed -- now, and only now, touch the output tree
os.makedirs(os.path.join(OUT, 'fonts'), exist_ok=True)
for _p, _data in PENDING:
    open(_p, 'wb').write(_data)
path = os.path.join(OUT, 'leo-program-finance.html')
open(path, 'w', encoding='utf-8').write(html)
print('wrote %s  (%d bytes)' % (path, len(html)))
print('fonts self-hosted: %d' % written)
print('hover classes: %d' % len(C.hover_rules))
for bad in ['unpkg.com', 'fonts.googleapis', 'fonts.gstatic', 'cdn.']:
    print('  %-18s %d' % (bad, html.count(bad)))
